version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.202:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "glog_benu:1:1,glog_chuxin:1:1"
    depends_on:
      - zookeeper
    container_name: kafka

  logstash:
    image: logstash:7.9.3
    restart: unless-stopped
    ports:
      - "9600:9600"
    volumes:
      - /data/docker-vol/logstash/config/:/usr/share/logstash/config/
      - /data/docker-vol/logstash/pipeline/:/usr/share/logstash/pipeline/
    depends_on:
      - kafka
      - elasticsearch
    container_name: logstash

  elasticsearch:
    image: elasticsearch:7.9.3
    restart: unless-stopped
    ports:
      - "9200:9200"
    volumes:
      - /data/docker-vol/elasticsearch/config/:/usr/share/elasticsearch/config/
    environment:
      discovery.type: single-node
    container_name: elasticsearch

  kibana:
    image: kibana:7.9.3
    restart: unless-stopped
    ports:
      - "5601:5601"
    volumes:
      - /data/docker-vol/kibana/config/:/usr/share/kibana/config/
    depends_on:
      - elasticsearch
    container_name: kibana

